### ISSUE TITLE
[BUG]: Fix the link in readme

### ISSUE THREAD

**Issue by Manobal-Singh-Bagady** [MSB-s-Projects/Generate-QR-code#29]
![image](https://user-images.githubusercontent.com/96862518/221444274-4c9bc2ff-d832-4826-8ee3-939b028f0ecd.png)

This link is wrong in the readme it needs to be changed.

**Comment by dhruv-porwal** [comment]
Sir assign this issue to me.

**Comment by Manobal-Singh-Bagady** [comment]
> Sir assign this issue to me.

assigned 👍🏼
