### ISSUE TITLE
[Enhancement]: The UI needs a changeover

### ISSUE THREAD

**Issue by Manobal-Singh-Bagady** [MSB-s-Projects/Generate-QR-code#3]
I created this app from a prebuilt TailwindCSS template I picked up from the internet. The UI needs improvements and good looks.

**Comment by Nikhil7174** [comment]
Please assign this issue to me

**Comment by Manobal-Singh-Bagady** [comment]
> Please assign this issue to me

Ok assigning it to you

**Comment by Nikhil7174** [comment]
@Manobal-Singh-Bagady I will change the background and make it look better and create a pull request of improved ui

**Comment by Manobal-Singh-Bagady** [comment]
> @Manobal-Singh-Bagady Can you please merge pr of issue #21 so that i can create a new pr for issue #3 as i have prepared a new UI for the website.
> 
> Original ![Screenshot (136)](https://user-images.githubusercontent.com/40711348/218660941-3bfe1994-b76f-4d09-bdbf-ef0a2c23dbc7.png)
> 
> Updated ![Screenshot (138)](https://user-images.githubusercontent.com/40711348/218661072-4f958680-7b9e-4edb-9d44-ab9d417e194c.png)

This looks amazing @Nikhil7174 GW please make the PR I will merge this design for sure.
