### ISSUE TITLE
[Bug]: frontend + backend for image-functionality

### ISSUE THREAD

**Issue by Manobal-Singh-Bagady** [MSB-s-Projects/Generate-QR-code#32]
The Frontend was created in #22. We need to link the backend to the front end in the image-functionality branch So that these labels start working.

![image](https://user-images.githubusercontent.com/96862518/222806845-0ccfee9d-199e-4d38-9680-8f2033641956.png)

**Comment by ugpec79** [comment]
Pls assign this to me
