### ISSUE TITLE
[Feature Request]: Need create QR code of links.

### ISSUE THREAD

**Issue by Manobal-Singh-Bagady** [MSB-s-Projects/Generate-QR-code#5]
Right now, the app only encodes plain text to QR codes. We need functionality so users can also create QR codes out of links.

The UI will also be needed to update:
 
we need something similar to this
![image](https://user-images.githubusercontent.com/96862518/215843713-884d5024-b48a-4ec1-b3d1-d76d489f4252.png)

there are two sections and the user can choose if they want to encode plain text or urls.

**Comment by ugpec79** [comment]
@Manobal-Singh-Bagady can u assign it to me

**Comment by Manobal-Singh-Bagady** [comment]
Alright @ugpec79 assigning it to you.

**Comment by ugpec79** [comment]
@Manobal-Singh-Bagady for url purpose same thing is working only u have to have different ui for both for categorisation else its  working for both

**Comment by ugpec79** [comment]
Thank u for the review

**Comment by Nitin98125** [comment]
Please assign it to me

**Comment by Manobal-Singh-Bagady** [comment]
> Please assign it to me

alright @Nitin98125 assigning it to you.

**Comment by Nitin98125** [comment]
i have made the PR plz review it @Manobal-Singh-Bagady
