### ISSUE TITLE
[Feature Request]: Create a footer for the website.

### ISSUE THREAD

**Issue by Manobal-Singh-Bagady** [MSB-s-Projects/Generate-QR-code#9]
Need to create a footer for the UI.

**Comment by Nikhil7174** [comment]
Please assign me this issue

**Comment by Manobal-Singh-Bagady** [comment]
> Please assign me this issue

@Nikhil7174 someone has already made a PR for this issue but has yet to ask for an assignment. I am waiting for their response. If they don't respond soon, I'll assign it to you.

**Comment by iamatifmoin** [comment]
@Nikhil7174 please assign me this issue if it has not been fixed.

**Comment by Nikhil7174** [comment]
@Manobal-Singh-Bagady Footer is ready can you please merge issue #3 so that i can create a new pr for this footer
![Screenshot (256)](https://user-images.githubusercontent.com/40711348/222879342-acb320ea-a785-4f2e-994c-255f23d4b002.png)
